language: node_js
sudo: required
before_install:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
install: true
before_script:
- export DOCKER_HOST="$HOST_NAME"
script:
- docker build -t $DOCKER_USERNAME/htmltest .
- docker push $DOCKER_USERNAME/htmltest
after_success:
- docker stop htmltest
- docker rm htmltest
- docker run -p 8088:80 -d --name htmltest $DOCKER_USERNAME/htmltest:latest
service: docker
env:
  global:
  - secure: S+P374dFQClxovG19x+Hv7UQqgSKIJ8gjsIFgWvdzqMVrbijw5lixJON4DTAY0hM6F4Fh3lwSqsLz30QT0ms8d290FaEfmQyCGzW1CvN0NXm5yHUMoa6SFi1R4YpiOzHpyqvY7FVwXUCT3/J8Cn24GdkMdrt1xGtdDNYIIBfBUkuZJmpFxk14Qx8ABoTz5GhHVkLyo7izb6NCl9sORZt6Lsp6m2CpxkmiTzTDoyFrjB8Sn7nNTMYeiL6XDla/Ei16I0qMw7zgljl5qHrzcqC1dIn2ufG11gnm8PBtzdJPfM18YhrmGV6qTsbNEDGRo8MNlpyzvNIL3kUWiMaAp8ayYZaswAFhRFlVRFqOzNlF10W2+coQr/ancDDXL85jH/VeB/9JaVH8MNIzTpLLZ0o8RV1s3CdWG7hdq0h+s0No2sOFKryXpzdDxMxc/QFBtjbEuwz6ETNFdGgpLmUSQkBh5bJFzaf9l2nOL3NDJnS/ZaiFYTa3CKMg9rRP8TzNlQiCHe/FAEVW3krrkNrmcv2F2mtQ5XdaDBcE8IewGBvYixVWaCH/1oJdcJtnZ3d3BXsWMx4Jy19sqyhwJFxm6eq7rEFT1CUIHZO7gTze1Q3NAkxUPUAgkgXS+NkUA7T4TO/piCg9e4st3HbEivS1siXBROmy2gILYbQocbvrO90zbE=
  - secure: ODbft49qFq7CXOGs12dueqTuxRWFW8p+8uM3VKfqgpEpXlWE4fch2Y8DfaHe/sB19ju2ab0On2+aL6ljMyHVER5JCSgJBi1E8I1aJRr9EEtStKzqBo3nXlgf1AjmlpPtQuOf2BvFhVRTwjJ1agQGOhCdOZNqWsDc0ETQpLNsx9G5CjCzjilZvuEqaaPHmW3hYYIRWUSjLoa8BDr+SLYvrMMvarZHKntAU5Rn0KSE+ut6KNIaNLGulxA26cPtQ7RlfjdlUyLQcJGd7HTLQS/5va/q9c5m04bQBo29fUiRordjjnWQkmTQMdwAgZFB7vkQFvA9R767xp6cjo5oBtgWJmy0KVB8xAQk5jpVq6qHr755z4rPwAW3PlmAVegDcx+bLSeLZKMV/hlnOdhFtWtB8nwWjR5geMNJGvMaXIn7MyjYB9jN54wLmyeuQjnRGxAsVdAKmxz6Mbb9fBftiKUx+GNk7HzxwCEih/2DbDnQ04pNPPThsAFXotZJkhm8ex00EAtP0C//Db5MfW8XqcCz5qwYoJt8dplUtEJv6NK655YbWzFGqC41Lx23U1A/vgdMrbnh1JyWp++C6NCYeUxSj18599fVZqonSmozL4fcl83x6ZTjicDzyw3mvxK5cO88Oo7pT19As4+MqdVs6xq6YdZM7rf3Ffu74bWQYgkzJWE=
dd:
  secure: T/BseRBPHnCUYldGAHrvhEfaFTDdKn4QKNGPQ9FgaJqtI5Ji/ojG9EX0Q9q9hI05psMsPoIVK/BFz5732q7u9xtiGYgXJ1ypLBiA0Rfehs+1FiohIBKmj514zAtvbrgdmeVW9X4L+uXk5RzdmcTNFxJlU78PsC2CLYHL+aLnQq/UrAf15H/Y8JbF1KFY3/DcZBaPm3QOL+TYsWe2PMVW9iSqFBCxCY1HQ+e4bd03gBtSLusGSZShSrGb9Z2qJhae9t5UAAcHYYWPFDUCj5tUS2pKj1FmbxZ2iMzrPHT4Zx7z0kiW38LEYu4MsHacUQ4ku/MvR0c3aXn8e9gy1uUgRdR0YY7Xoxe0ptXnlCcedZfhuSy5InhGUMBJdOu3/TbMu/oxLM2fh+WYJwksJYD8xIGxfbTKCW7MiwEHAUopDQ+/Nh6G05wXKVStCpbMAzKB5zBQ1/Uhutya/vci6+Yv/k8xu8xSOjkgB8vdQalnj/BHfJncD8Pxy+sYiOAzdV+roa+FTQekvZKPqzJtA6UJAxKTMiOwZi39R+ltM+HP33VlNav9lhYO/hgN0BvQNwcAQs4m9znG8Gt+m9vd0LPBhxnq/AgdF9lrK42hT74tD2d79qsesRHnOjUkH9G4QJ3/yyOx0XFrHo+/EbBzayv9FrV/4U9yI+glxC9ImKuU2DI=
